name: qwant_api
version: 0.1.1
description: An unofficial api for helping using Qwant's search. This package is for helping developers to make some queries with the Qwant's engine. 
homepage: https://github.com/zemoa/qwant-api-dart/

environment:
  sdk: '>=2.7.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
